# Generated by Django 5.2.5 on 2025-11-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slooze", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
