# Generated by Django 5.2.5 on 2025-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slooze", "0003_product_description_alter_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(),
        ),
    ]
