# Generated by Django 5.2.5 on 2025-11-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slooze", "0004_remove_product_description_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
